package com.myhopu.mapper;

import com.myhopu.entity.CheckDetail;
import com.myhopu.entity.CheckDetailExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CheckDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDETAIL
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    long countByExample(CheckDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDETAIL
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    int deleteByExample(CheckDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDETAIL
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long checkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDETAIL
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    int insert(CheckDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDETAIL
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    int insertSelective(CheckDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDETAIL
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    List<CheckDetail> selectByExample(CheckDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDETAIL
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    CheckDetail selectByPrimaryKey(Long checkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDETAIL
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") CheckDetail record, @Param("example") CheckDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDETAIL
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    int updateByExample(@Param("record") CheckDetail record, @Param("example") CheckDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDETAIL
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(CheckDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDETAIL
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    int updateByPrimaryKey(CheckDetail record);

	void insertPitch(List<CheckDetail> cdList);

	List<CheckDetail> selectByCheckCodeTime(Map<String, Object> mapQuery);
}