package com.myhopu.mapper;

import com.myhopu.entity.CheckDateOption;
import com.myhopu.entity.CheckDateOptionExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CheckDateOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDATEOPTION
     *
     * @mbg.generated Fri Nov 16 09:08:24 GMT+08:00 2018
     */
    long countByExample(CheckDateOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDATEOPTION
     *
     * @mbg.generated Fri Nov 16 09:08:24 GMT+08:00 2018
     */
    int deleteByExample(CheckDateOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDATEOPTION
     *
     * @mbg.generated Fri Nov 16 09:08:24 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long settingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDATEOPTION
     *
     * @mbg.generated Fri Nov 16 09:08:24 GMT+08:00 2018
     */
    int insert(CheckDateOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDATEOPTION
     *
     * @mbg.generated Fri Nov 16 09:08:24 GMT+08:00 2018
     */
    int insertSelective(CheckDateOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDATEOPTION
     *
     * @mbg.generated Fri Nov 16 09:08:24 GMT+08:00 2018
     */
    List<CheckDateOption> selectByExample(CheckDateOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDATEOPTION
     *
     * @mbg.generated Fri Nov 16 09:08:24 GMT+08:00 2018
     */
    CheckDateOption selectByPrimaryKey(Long settingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDATEOPTION
     *
     * @mbg.generated Fri Nov 16 09:08:24 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") CheckDateOption record, @Param("example") CheckDateOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDATEOPTION
     *
     * @mbg.generated Fri Nov 16 09:08:24 GMT+08:00 2018
     */
    int updateByExample(@Param("record") CheckDateOption record, @Param("example") CheckDateOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDATEOPTION
     *
     * @mbg.generated Fri Nov 16 09:08:24 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(CheckDateOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECKDATEOPTION
     *
     * @mbg.generated Fri Nov 16 09:08:24 GMT+08:00 2018
     */
    int updateByPrimaryKey(CheckDateOption record);

	List<CheckDateOption> selectByYearMounth(Map<String, Object> mapQuery);
}