package com.myhopu.mapper;

import com.myhopu.entity.Leave;
import com.myhopu.entity.LeaveExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface LeaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LEAVE
     *
     * @mbg.generated Tue Nov 13 14:09:01 GMT+08:00 2018
     */
    long countByExample(LeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LEAVE
     *
     * @mbg.generated Tue Nov 13 14:09:01 GMT+08:00 2018
     */
    int deleteByExample(LeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LEAVE
     *
     * @mbg.generated Tue Nov 13 14:09:01 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long leaveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LEAVE
     *
     * @mbg.generated Tue Nov 13 14:09:01 GMT+08:00 2018
     */
    int insert(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LEAVE
     *
     * @mbg.generated Tue Nov 13 14:09:01 GMT+08:00 2018
     */
    int insertSelective(Leave record);

    public Long selectCountByMapWithUser(Map<String, Object> mapQuery);
    
    public List<Object> selectByMapWithUser(Map<String,Object> map);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LEAVE
     *
     * @mbg.generated Tue Nov 13 14:09:01 GMT+08:00 2018
     */
    List<Leave> selectByExample(LeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LEAVE
     *
     * @mbg.generated Tue Nov 13 14:09:01 GMT+08:00 2018
     */
    Leave selectByPrimaryKey(Long leaveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LEAVE
     *
     * @mbg.generated Tue Nov 13 14:09:01 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Leave record, @Param("example") LeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LEAVE
     *
     * @mbg.generated Tue Nov 13 14:09:01 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Leave record, @Param("example") LeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LEAVE
     *
     * @mbg.generated Tue Nov 13 14:09:01 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LEAVE
     *
     * @mbg.generated Tue Nov 13 14:09:01 GMT+08:00 2018
     */
    int updateByPrimaryKey(Leave record);

	Long getCountByDid(Map<String, Object> mapQuery);

	List<Object> getUserLeaveListByDid(Map<String, Object> mapQuery);

	Long getCountAll();

	List<Object> getUserLeaveListAll(Map<String, Object> mapQuery);

	List<Leave> selectListByStatus(Long status);

	List<Leave> selectByUseridTimeStart(Map<String, Object> map);
}