package com.myhopu.entity;

import java.util.Date;

public class CheckDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CHECKDETAIL.CHECK_ID
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    private Long checkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CHECKDETAIL.DEPT_ID
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    private Long deptId;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CHECKDETAIL.USER_ID
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CHECKDETAIL.CHECK_CODE
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    private Long checkCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CHECKDETAIL.TIME_CHECK
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    private Date timeCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CHECKDETAIL.CHECK_NUM
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    private Long checkNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CHECKDETAIL.CHECK_TYPE
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    private String checkType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CHECKDETAIL.CHECK_ID
     *
     * @return the value of TB_CHECKDETAIL.CHECK_ID
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    public Long getCheckId() {
        return checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CHECKDETAIL.CHECK_ID
     *
     * @param checkId the value for TB_CHECKDETAIL.CHECK_ID
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    public void setCheckId(Long checkId) {
        this.checkId = checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CHECKDETAIL.DEPT_ID
     *
     * @return the value of TB_CHECKDETAIL.DEPT_ID
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CHECKDETAIL.DEPT_ID
     *
     * @param deptId the value for TB_CHECKDETAIL.DEPT_ID
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CHECKDETAIL.USER_ID
     *
     * @return the value of TB_CHECKDETAIL.USER_ID
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CHECKDETAIL.USER_ID
     *
     * @param userId the value for TB_CHECKDETAIL.USER_ID
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CHECKDETAIL.CHECK_CODE
     *
     * @return the value of TB_CHECKDETAIL.CHECK_CODE
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    public Long getCheckCode() {
        return checkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CHECKDETAIL.CHECK_CODE
     *
     * @param checkCode the value for TB_CHECKDETAIL.CHECK_CODE
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    public void setCheckCode(Long checkCode) {
        this.checkCode = checkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CHECKDETAIL.TIME_CHECK
     *
     * @return the value of TB_CHECKDETAIL.TIME_CHECK
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    public Date getTimeCheck() {
        return timeCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CHECKDETAIL.TIME_CHECK
     *
     * @param timeCheck the value for TB_CHECKDETAIL.TIME_CHECK
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    public void setTimeCheck(Date timeCheck) {
        this.timeCheck = timeCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CHECKDETAIL.CHECK_NUM
     *
     * @return the value of TB_CHECKDETAIL.CHECK_NUM
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    public Long getCheckNum() {
        return checkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CHECKDETAIL.CHECK_NUM
     *
     * @param checkNum the value for TB_CHECKDETAIL.CHECK_NUM
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    public void setCheckNum(Long checkNum) {
        this.checkNum = checkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CHECKDETAIL.CHECK_TYPE
     *
     * @return the value of TB_CHECKDETAIL.CHECK_TYPE
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    public String getCheckType() {
        return checkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CHECKDETAIL.CHECK_TYPE
     *
     * @param checkType the value for TB_CHECKDETAIL.CHECK_TYPE
     *
     * @mbg.generated Sat Nov 17 17:15:26 GMT+08:00 2018
     */
    public void setCheckType(String checkType) {
        this.checkType = checkType == null ? null : checkType.trim();
    }

	@Override
	public String toString() {
		return "CheckDetail [checkId=" + checkId + ", deptId=" + deptId + ", userId=" + userId + ", checkCode="
				+ checkCode + ", timeCheck=" + timeCheck + ", checkNum=" + checkNum + ", checkType=" + checkType + "]";
	}
    
    
    
}